server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    username: basler182
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
springdoc:
  swagger-ui:
    path: /apidoc
    display-request-duration: true
    disable-swagger-default-url: true
    csrf:
      enabled: true
    operations-sorter: method
    tags-sorter: alpha
    api-docs:
      path: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false