package de.runtimeterror.customer.rights;

public enum CustomerRights {
    EDIT_CUSTOMER, DELETE_CUSTOMER, CREATE_CUSTOMER, VIEW_CUSTOMER,
    VIEW_CUSTOMER_LIST, DELETE_CUSTOMER_LIST, CREATE_CUSTOMER_LIST, EDIT_CUSTOMER_LIST
}
